export const STOCK_TRANSACTION_CREATE_REQUEST =
  'STOCK_TRANSACTION_CREATE_REQUEST';
export const STOCK_TRANSACTION_CREATE_SUCCESS =
  'STOCK_TRANSACTION_CREATE_SUCCESS';
export const STOCK_TRANSACTION_CREATE_FAIL = 'STOCK_TRANSACTION_CREATE_FAIL';
export const STOCK_TRANSACTION_CREATE_RESET = 'STOCK_TRANSACTION_CREATE_RESET';
