export const STOCK_TRANSACTION_CREATE_REQUEST =
  'STOCK_TRANSACTION_CREATE_REQUEST';
export const STOCK_TRANSACTION_CREATE_SUCCESS =
  'STOCK_TRANSACTION_CREATE_SUCCESS';
export const STOCK_TRANSACTION_CREATE_FAIL = 'STOCK_TRANSACTION_CREATE_FAIL';
export const STOCK_TRANSACTION_CREATE_RESET = 'STOCK_TRANSACTION_CREATE_RESET';

export const STOCK_PORTIFOLIO_REQUEST = 'STOCK_PORTIFOLIO_REQUEST';
export const STOCK_PORTIFOLIO_SUCCESS = 'STOCK_PORTIFOLIO_SUCCESS';
export const STOCK_PORTIFOLIO_FAIL = 'STOCK_PORTIFOLIO_FAIL';
